/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LockedRouteImport } from './routes/locked'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUserscopy2RouteImport } from './routes/_app.users copy 2'
import { Route as AppUserscopyRouteImport } from './routes/_app.users copy'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppTeamscopyRouteImport } from './routes/_app.teams copy'
import { Route as AppTeamsRouteImport } from './routes/_app.teams'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppQuotesRouteImport } from './routes/_app.quotes'
import { Route as AppOnboardingRouteImport } from './routes/_app.onboarding'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppLoadscopyRouteImport } from './routes/_app.loads copy'
import { Route as AppLoadsRouteImport } from './routes/_app.loads'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppInvoicesRouteImport } from './routes/_app.invoices'
import { Route as AppFollowupsRouteImport } from './routes/_app.followups'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppCommissionsRouteImport } from './routes/_app.commissions'
import { Route as AppCarriersRouteImport } from './routes/_app.carriers'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppApprovalscopyRouteImport } from './routes/_app.approvals copy'
import { Route as AppApprovalsRouteImport } from './routes/_app.approvals'
import { Route as AppAdmincopyRouteImport } from './routes/_app.admin copy'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppActivitycopyRouteImport } from './routes/_app.activity copy'
import { Route as AppActivityRouteImport } from './routes/_app.activity'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LockedRoute = LockedRouteImport.update({
  id: '/locked',
  path: '/locked',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUserscopy2Route = AppUserscopy2RouteImport.update({
  id: '/users copy 2',
  path: '/users copy 2',
  getParentRoute: () => AppRoute,
} as any)
const AppUserscopyRoute = AppUserscopyRouteImport.update({
  id: '/users copy',
  path: '/users copy',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamscopyRoute = AppTeamscopyRouteImport.update({
  id: '/teams copy',
  path: '/teams copy',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsRoute = AppTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesRoute = AppQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLoadscopyRoute = AppLoadscopyRouteImport.update({
  id: '/loads copy',
  path: '/loads copy',
  getParentRoute: () => AppRoute,
} as any)
const AppLoadsRoute = AppLoadsRouteImport.update({
  id: '/loads',
  path: '/loads',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppFollowupsRoute = AppFollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCommissionsRoute = AppCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AppRoute,
} as any)
const AppCarriersRoute = AppCarriersRouteImport.update({
  id: '/carriers',
  path: '/carriers',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalscopyRoute = AppApprovalscopyRouteImport.update({
  id: '/approvals copy',
  path: '/approvals copy',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAdmincopyRoute = AppAdmincopyRouteImport.update({
  id: '/admin copy',
  path: '/admin copy',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppActivitycopyRoute = AppActivitycopyRouteImport.update({
  id: '/activity copy',
  path: '/activity copy',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/locked': typeof LockedRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activity': typeof AppActivityRoute
  '/activity copy': typeof AppActivitycopyRoute
  '/admin': typeof AppAdminRoute
  '/admin copy': typeof AppAdmincopyRoute
  '/approvals': typeof AppApprovalsRoute
  '/approvals copy': typeof AppApprovalscopyRoute
  '/audit': typeof AppAuditRoute
  '/carriers': typeof AppCarriersRoute
  '/commissions': typeof AppCommissionsRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/followups': typeof AppFollowupsRoute
  '/invoices': typeof AppInvoicesRoute
  '/leads': typeof AppLeadsRoute
  '/loads': typeof AppLoadsRoute
  '/loads copy': typeof AppLoadscopyRoute
  '/notifications': typeof AppNotificationsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/quotes': typeof AppQuotesRoute
  '/reports': typeof AppReportsRoute
  '/search': typeof AppSearchRoute
  '/teams': typeof AppTeamsRoute
  '/teams copy': typeof AppTeamscopyRoute
  '/users': typeof AppUsersRoute
  '/users copy': typeof AppUserscopyRoute
  '/users copy 2': typeof AppUserscopy2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/locked': typeof LockedRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activity': typeof AppActivityRoute
  '/activity copy': typeof AppActivitycopyRoute
  '/admin': typeof AppAdminRoute
  '/admin copy': typeof AppAdmincopyRoute
  '/approvals': typeof AppApprovalsRoute
  '/approvals copy': typeof AppApprovalscopyRoute
  '/audit': typeof AppAuditRoute
  '/carriers': typeof AppCarriersRoute
  '/commissions': typeof AppCommissionsRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/followups': typeof AppFollowupsRoute
  '/invoices': typeof AppInvoicesRoute
  '/leads': typeof AppLeadsRoute
  '/loads': typeof AppLoadsRoute
  '/loads copy': typeof AppLoadscopyRoute
  '/notifications': typeof AppNotificationsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/quotes': typeof AppQuotesRoute
  '/reports': typeof AppReportsRoute
  '/search': typeof AppSearchRoute
  '/teams': typeof AppTeamsRoute
  '/teams copy': typeof AppTeamscopyRoute
  '/users': typeof AppUsersRoute
  '/users copy': typeof AppUserscopyRoute
  '/users copy 2': typeof AppUserscopy2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/locked': typeof LockedRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/activity copy': typeof AppActivitycopyRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/admin copy': typeof AppAdmincopyRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/approvals copy': typeof AppApprovalscopyRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/carriers': typeof AppCarriersRoute
  '/_app/commissions': typeof AppCommissionsRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/followups': typeof AppFollowupsRoute
  '/_app/invoices': typeof AppInvoicesRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/loads': typeof AppLoadsRoute
  '/_app/loads copy': typeof AppLoadscopyRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/quotes': typeof AppQuotesRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/teams': typeof AppTeamsRoute
  '/_app/teams copy': typeof AppTeamscopyRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/users copy': typeof AppUserscopyRoute
  '/_app/users copy 2': typeof AppUserscopy2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/locked'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/activity'
    | '/activity copy'
    | '/admin'
    | '/admin copy'
    | '/approvals'
    | '/approvals copy'
    | '/audit'
    | '/carriers'
    | '/commissions'
    | '/customers'
    | '/dashboard'
    | '/documents'
    | '/followups'
    | '/invoices'
    | '/leads'
    | '/loads'
    | '/loads copy'
    | '/notifications'
    | '/onboarding'
    | '/quotes'
    | '/reports'
    | '/search'
    | '/teams'
    | '/teams copy'
    | '/users'
    | '/users copy'
    | '/users copy 2'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/locked'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/activity'
    | '/activity copy'
    | '/admin'
    | '/admin copy'
    | '/approvals'
    | '/approvals copy'
    | '/audit'
    | '/carriers'
    | '/commissions'
    | '/customers'
    | '/dashboard'
    | '/documents'
    | '/followups'
    | '/invoices'
    | '/leads'
    | '/loads'
    | '/loads copy'
    | '/notifications'
    | '/onboarding'
    | '/quotes'
    | '/reports'
    | '/search'
    | '/teams'
    | '/teams copy'
    | '/users'
    | '/users copy'
    | '/users copy 2'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/locked'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/_app/activity'
    | '/_app/activity copy'
    | '/_app/admin'
    | '/_app/admin copy'
    | '/_app/approvals'
    | '/_app/approvals copy'
    | '/_app/audit'
    | '/_app/carriers'
    | '/_app/commissions'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/followups'
    | '/_app/invoices'
    | '/_app/leads'
    | '/_app/loads'
    | '/_app/loads copy'
    | '/_app/notifications'
    | '/_app/onboarding'
    | '/_app/quotes'
    | '/_app/reports'
    | '/_app/search'
    | '/_app/teams'
    | '/_app/teams copy'
    | '/_app/users'
    | '/_app/users copy'
    | '/_app/users copy 2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LockedRoute: typeof LockedRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locked': {
      id: '/locked'
      path: '/locked'
      fullPath: '/locked'
      preLoaderRoute: typeof LockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users copy 2': {
      id: '/_app/users copy 2'
      path: '/users copy 2'
      fullPath: '/users copy 2'
      preLoaderRoute: typeof AppUserscopy2RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users copy': {
      id: '/_app/users copy'
      path: '/users copy'
      fullPath: '/users copy'
      preLoaderRoute: typeof AppUserscopyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams copy': {
      id: '/_app/teams copy'
      path: '/teams copy'
      fullPath: '/teams copy'
      preLoaderRoute: typeof AppTeamscopyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams': {
      id: '/_app/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AppTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes': {
      id: '/_app/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof AppQuotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loads copy': {
      id: '/_app/loads copy'
      path: '/loads copy'
      fullPath: '/loads copy'
      preLoaderRoute: typeof AppLoadscopyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loads': {
      id: '/_app/loads'
      path: '/loads'
      fullPath: '/loads'
      preLoaderRoute: typeof AppLoadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/followups': {
      id: '/_app/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof AppFollowupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/commissions': {
      id: '/_app/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof AppCommissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carriers': {
      id: '/_app/carriers'
      path: '/carriers'
      fullPath: '/carriers'
      preLoaderRoute: typeof AppCarriersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals copy': {
      id: '/_app/approvals copy'
      path: '/approvals copy'
      fullPath: '/approvals copy'
      preLoaderRoute: typeof AppApprovalscopyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin copy': {
      id: '/_app/admin copy'
      path: '/admin copy'
      fullPath: '/admin copy'
      preLoaderRoute: typeof AppAdmincopyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity copy': {
      id: '/_app/activity copy'
      path: '/activity copy'
      fullPath: '/activity copy'
      preLoaderRoute: typeof AppActivitycopyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppActivitycopyRoute: typeof AppActivitycopyRoute
  AppAdminRoute: typeof AppAdminRoute
  AppAdmincopyRoute: typeof AppAdmincopyRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppApprovalscopyRoute: typeof AppApprovalscopyRoute
  AppAuditRoute: typeof AppAuditRoute
  AppCarriersRoute: typeof AppCarriersRoute
  AppCommissionsRoute: typeof AppCommissionsRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppFollowupsRoute: typeof AppFollowupsRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppLoadsRoute: typeof AppLoadsRoute
  AppLoadscopyRoute: typeof AppLoadscopyRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppQuotesRoute: typeof AppQuotesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSearchRoute: typeof AppSearchRoute
  AppTeamsRoute: typeof AppTeamsRoute
  AppTeamscopyRoute: typeof AppTeamscopyRoute
  AppUsersRoute: typeof AppUsersRoute
  AppUserscopyRoute: typeof AppUserscopyRoute
  AppUserscopy2Route: typeof AppUserscopy2Route
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppActivitycopyRoute: AppActivitycopyRoute,
  AppAdminRoute: AppAdminRoute,
  AppAdmincopyRoute: AppAdmincopyRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppApprovalscopyRoute: AppApprovalscopyRoute,
  AppAuditRoute: AppAuditRoute,
  AppCarriersRoute: AppCarriersRoute,
  AppCommissionsRoute: AppCommissionsRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppFollowupsRoute: AppFollowupsRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppLoadsRoute: AppLoadsRoute,
  AppLoadscopyRoute: AppLoadscopyRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppQuotesRoute: AppQuotesRoute,
  AppReportsRoute: AppReportsRoute,
  AppSearchRoute: AppSearchRoute,
  AppTeamsRoute: AppTeamsRoute,
  AppTeamscopyRoute: AppTeamscopyRoute,
  AppUsersRoute: AppUsersRoute,
  AppUserscopyRoute: AppUserscopyRoute,
  AppUserscopy2Route: AppUserscopy2Route,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LockedRoute: LockedRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
